CREATE TABLE [dbo].[video_cumm_stats] (

	[LastestSnapshot] date NULL, 
	[Video ID] varchar(200) NULL, 
	[Channel ID] varchar(200) NULL, 
	[Release Date] date NULL, 
	[Scheduled Start Time] varchar(300) NULL, 
	[Title] varchar(300) NULL, 
	[Duration(mins)] int NULL, 
	[Thumbnail] varchar(300) NULL, 
	[URL] varchar(300) NULL, 
	[views_latest] int NULL, 
	[likes_latest] int NULL, 
	[comments_latest] int NULL, 
	[viewsPrevDay] int NULL, 
	[likesPrevDay] int NULL, 
	[commentsPrevDay] int NULL, 
	[views7Days] int NULL, 
	[likes7Days] int NULL, 
	[comments7Days] int NULL, 
	[views30Days] int NULL, 
	[likes30Days] int NULL, 
	[comments30Days] int NULL, 
	[delta_views_prevDay] int NULL, 
	[delta_likes_prevDay] int NULL, 
	[delta_comments_prevDay] int NULL, 
	[delta_views_7Days] int NULL, 
	[delta_likes_7Days] int NULL, 
	[delta_comments_7Days] int NULL, 
	[delta_views_30Days] int NULL, 
	[delta_likes_30Days] int NULL, 
	[delta_comments_30Days] int NULL, 
	[growth_rate_views_prevDay] decimal(10,4) NULL, 
	[growth_rate_likes_prevDay] decimal(10,4) NULL, 
	[growth_rate_comments_prevDay] decimal(10,4) NULL, 
	[growth_rate_views_7Days] decimal(10,4) NULL, 
	[growth_rate_likes_7Days] decimal(10,4) NULL, 
	[growth_rate_comments_7Days] decimal(10,4) NULL, 
	[growth_rate_views_30Days] decimal(10,4) NULL, 
	[growth_rate_likes_30Days] decimal(10,4) NULL, 
	[growth_rate_comments_30Days] decimal(10,4) NULL
);